apiVersion: v1
kind: Pod
metadata:
  name: multitool
  namespace: default
  labels:
    app: multitool
spec:
  containers:
  - name: multitool
    image: praqma/network-multitool:latest
    ports:
    - containerPort: 80
      name: http
    - containerPort: 443
      name: https
    env:
    - name: HTTP_PORT
      value: "80"
    - name: HTTPS_PORT
      value: "443"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    command:
    - /bin/bash
    - -c
    - |
      echo "Multitool pod started"
      echo "Available tools: curl, wget, nslookup, dig, ping, traceroute, netstat, ss, iperf3, tcpdump"
      echo "Pod IP: $(hostname -i)"
      echo "Node: $HOSTNAME"
      nginx -g "daemon off;"
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: multitool-service
  namespace: default
  labels:
    app: multitool
spec:
  selector:
    app: multitool
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  type: ClusterIP
