# Multitool DaemonSet for DNS and Redis testing
# Provides dig, nslookup, curl, redis-cli, and other network tools
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool
  namespace: default
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: HTTP_PORT
          value: "80"
        - name: HTTPS_PORT
          value: "443"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        command:
        - /bin/bash
        - -c
        - |
          echo "Installing redis-cli..."
          apk add --no-cache redis > /dev/null 2>&1
          echo "Multitool pod started on node: $HOSTNAME"
          echo "Available tools: curl, wget, nslookup, dig, ping, traceroute, netstat, ss, iperf3, tcpdump, redis-cli"
          echo "Pod IP: $(hostname -i)"
          nginx -g "daemon off;"
      restartPolicy: Always
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
