---
# Pod with dynamic IP (default behavior)
apiVersion: v1
kind: Pod
metadata:
  name: dynamic-pod
  labels:
    app: dynamic-pod
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sleep", "3600"]

