---
# Pod with static IP using Calico annotation
apiVersion: v1
kind: Pod
metadata:
  name: static-pod
  labels:
    app: static-pod
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"192.168.100.10\"]"
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sleep", "3600"]

