apiVersion: v1
kind: Pod
metadata:
  name: macvlan-test-pod
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: vlan20-macvlan
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep", "infinity"]
