# Calico Installation with dual-stack (IPv4 + IPv6) pod networking
# Pods receive both IPv4 and IPv6 addresses
# IPv6 traffic between nodes is encapsulated in VXLAN (works on IPv4-only infrastructure)

apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
      # IPv4 IP Pool
      - name: default-ipv4-ippool
        blockSize: 26
        cidr: 192.168.0.0/16
        encapsulation: VXLANCrossSubnet
        natOutgoing: Enabled
        nodeSelector: all()

      # IPv6 IP Pool
      # VXLAN encapsulation allows IPv6 pods even when nodes only have IPv4
      - name: default-ipv6-ippool
        blockSize: 122
        cidr: fd00:10:244::/48
        encapsulation: VXLAN
        natOutgoing: Enabled
        nodeSelector: all()

---

apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}
