# NetworkAttachmentDefinitions for VLAN 100 and VLAN 200
# Uses Bridge CNI with VLAN tagging
# Requires VLAN-aware bridge (br-multus) on each node
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan100-net
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vlan100-net",
      "type": "bridge",
      "bridge": "br-multus",
      "vlan": 100,
      "isGateway": false,
      "ipMasq": false,
      "hairpinMode": false,
      "ipam": {
        "type": "host-local",
        "subnet": "10.10.100.0/24",
        "rangeStart": "10.10.100.100",
        "rangeEnd": "10.10.100.200",
        "gateway": "10.10.100.1"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan200-net
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vlan200-net",
      "type": "bridge",
      "bridge": "br-multus",
      "vlan": 200,
      "isGateway": false,
      "ipMasq": false,
      "hairpinMode": false,
      "ipam": {
        "type": "host-local",
        "subnet": "10.10.200.0/24",
        "rangeStart": "10.10.200.100",
        "rangeEnd": "10.10.200.200",
        "gateway": "10.10.200.1"
      }
    }
---
# Example test pod using both VLANs
apiVersion: v1
kind: Pod
metadata:
  name: test-vlan-pod
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: vlan100-net, vlan200-net
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep", "infinity"]
---
# Example DaemonSet for testing on all nodes
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vlan-test-ds
  namespace: default
spec:
  selector:
    matchLabels:
      app: vlan-test
  template:
    metadata:
      labels:
        app: vlan-test
      annotations:
        k8s.v1.cni.cncf.io/networks: vlan100-net, vlan200-net
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["sleep", "infinity"]

